
import { Octokit } from 'octokit';

export async function publishToGitHub(content: string, slug: string) {
    if (!process.env.GITHUB_TOKEN) {
        console.error("GITHUB_TOKEN is missing");
        return false;
    }

    const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

    // Clean slug
    const cleanSlug = slug.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
    const branchName = `post/${cleanSlug}-${Date.now()}`; // Unique branch
    const path = `src/content/blog/${cleanSlug}.mdx`;
    const message = `feat(blog): draft ${cleanSlug}`;

    const owner = process.env.GITHUB_OWNER || "Eswar-cdy";
    const repo = process.env.GITHUB_REPO || "Portfolio";

    try {
        console.log(`🤖 Starting Safety Workflow for: ${cleanSlug}`);

        // 1. Get SHA of 'main' to branch off from
        // Note: Assuming 'main' is the default branch. Adjust if 'master'.
        const { data: refData } = await octokit.request('GET /repos/{owner}/{repo}/git/ref/heads/main', {
            owner,
            repo,
        });
        const mainSha = refData.object.sha;

        // 2. Create new Branch
        await octokit.request('POST /repos/{owner}/{repo}/git/refs', {
            owner,
            repo,
            ref: `refs/heads/${branchName}`,
            sha: mainSha,
        });
        console.log(`✅ Created branch: ${branchName}`);

        // 3. Create File on that Branch
        await octokit.request('PUT /repos/{owner}/{repo}/contents/{path}', {
            owner,
            repo,
            path,
            message,
            content: Buffer.from(content).toString('base64'),
            branch: branchName, // Important: Commit to branch!
            committer: {
                name: 'Antigravity AI Agent',
                email: 'agent@antigravity.ai'
            },
            author: {
                name: 'Antigravity AI Agent',
                email: 'agent@antigravity.ai'
            }
        });
        console.log(`✅ Committed file to ${branchName}`);

        // 4. Create Pull Request
        const { data: prData } = await octokit.request('POST /repos/{owner}/{repo}/pulls', {
            owner,
            repo,
            title: `[AI Draft] ${cleanSlug}`,
            body: `
## 🤖 Automated Blog Draft
**Topic**: ${cleanSlug}

### Review Checklist
- [ ] Tone check (Does it sound like Eswar?)
- [ ] Accuracy check (Hallucinations?)
- [ ] Image Prompt (See Frontmatter)

*Generated by Portfolio V3 Agent*
            `,
            head: branchName,
            base: 'main',
            maintainer_can_modify: true,
        });

        console.log(`🎉 PR Created Successfully: ${prData.html_url}`);
        return true;
    } catch (error) {
        console.error("Error in Safety Workflow:", error);
        return false;
    }
}
